server:
  port: 8084

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: ZDM0ZGUyYjM0ZGUyYjM0ZGUyYjM0ZGUyYjM0ZGUyYjM0ZGUyYjM0ZGUyYjM0ZGUyYg==
  expiration: 86400000