server:
  port: 8083

spring:
  #application:
    #name: rental-service
  datasource:
    url: jdbc:postgresql://localhost:5432/rental_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka