server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - OPTIONS
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/books/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: rental-service
          uri: lb://rental-service
          predicates:
            - Path=/api/rentals/**

        - id: openapi
          uri: http://localhost:8080
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    urls:
      - name: user-service
        url: /v3/api-docs/user-service
      - name: book-service
        url: /v3/api-docs/book-service
      - name: rental-service
        url: /v3/api-docs/rental-service

#jwt:
 # secret: ZDM0ZGUyYjM0ZGUyYjM0ZGUyYjM0ZGUyYjM0ZGUyYjM0ZGUyYjM0ZGUyYjM0ZGUyYg==