server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/books/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: rental-service
          uri: lb://rental-service
          predicates:
            - Path=/api/rentals/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka